### ISSUE TITLE
Error after bin/rake db:migrate

### ISSUE THREAD

**Issue by 00Bock** [InnoZ/RubyCars#16]
Hey, ich kriege immer ein Problem beim durchlaufen von bin/rake db:migrate ->
```
bbock@InnoZinOz:~/Repositories/RubyCars$ chruby
 * ruby-2.1.5
   ruby-2.3.0
   ruby-2.1.5
   ruby-2.1.9
   ruby-2.3.0
bbock@InnoZinOz:~/Repositories/RubyCars$ bin/rake db:migrate RAILS_ENV=development
/usr/bin/env: ‘ruby2.1’: No such file or directory
```

**Comment by 00Bock** [comment]
liegt das vielleicht daran, dass ich ruby 2.1.5 einmal als Superuser und einmal ohne installiert habe?

**Comment by BenSto** [comment]
Kann man per Ferndiagnose schwer beantworten, ich würde allerdings empfehlen, dass wir rvm zur ruby installation und für die ruby versionsverwaltung nutzen. Glaube das nutzt @kjoscha auch und ich ebenfalls. Dann ist es einfacher solche Sachen nachzuvollziehen.

**Comment by 00Bock** [comment]
Ich bin aber der Anleitung unter dem Link im Read Me gefolgt (ryanbigg.com/2014/10/ubuntu-ruby-ruby-install-chruby-and-you). Da wird chruby verwendet. Ich weiss nicht, ob sich das nicht beisst wenn ich rmv und chruby nutze? Was denkst du?

**Comment by BenSto** [comment]
> get the common ruby version e.g. 2.1 at the moment (installation via RVM recommended or according 
to this post: ryanbigg.com/2014/10/ubuntu-ruby-ruby-install-chruby-and-you// )

Hier steht doch RVM **oder** der Link. Ich weiß nicht, von wem diese Anleitung mit chruby ist und kenne mich folglich damit nicht aus. Ich würde aber meinen, dass sich beides zusammen beißt, ja.

**Comment by 00Bock** [comment]
ok...
