### ISSUE TITLE
Ram-Overload auf Server

### ISSUE THREAD

**Issue by kjoscha** [InnoZ/RubyCars#8]
Uberspace schreibt:

> Dein Prozess ruby hat über 607MB RAM in
> Anspruch genommen und damit stößt du an unser Limit

Daher wurde der Prozess beendet.

**Comment by 00Bock** [comment]
heute oder beim letzten Mal?

**Comment by 00Bock** [comment]
ah, ich sehe: vorgestern schon... Mehr Hinweise als Prozess 'ruby' gibt es nicht?

**Comment by kjoscha** [comment]
Samstag

**Comment by kjoscha** [comment]
leider nicht. aber wird sich schon herausfinden lassen.

**Comment by kjoscha** [comment]
Der Ram läuft tatsächlich ganz langsam voll über viele Tage. 

```
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                      
12790 innoz     20   0  209m  24m  21m S 50.4  0.1   1361:44 postgres                     
 9102 innoz     20   0  635m 388m 5228 S 34.1  1.6 844:56.31 ruby    
```

Das sind nun schon wieder 388mb, daher habe ich den Task neu gestartet. Was könnte da denn Ram verbrauchen?

**Comment by BenSto** [comment]
Kann ja eigentlich nur am neuen Log liegen. Das war ja die einzige Änderung bevor das Problem aufgetreten ist.

**Comment by kjoscha** [comment]
@BenSto schaust du dir das eigentlich noch an? Ist vielleich einfacher, weil du das Logging ja eingebaut hast. Wenn du aber garkeine Zeit findest, kann ich es auch versuchen...

**Comment by BenSto** [comment]
Nein ich habe es mir nicht nochmal angeschaut. Ich kann es wie gesagt auch nicht ganz nachvollziehen, warum die RAM Auslastung dort anscheinend mit jedem Durchlauf zunimmt. Der task `scrape` ruft ja nur den infinite loop auf. Ich denke, ich werde auch ehrlich gesagt wenn erst gegen Ende nächster Woche dazu kommen mich damit zu beschäftigen... :-(

**Comment by BenSto** [comment]
Wir könnten versuche den Garbage Collector alle paar Durchläufe (100 o.ä.) manuell zu aktivieren, in der Hoffnung das er bestehende Ruby Objekte aufräumt.

Sprich sowas in Infinite Loop einbauen:

```
class InfiniteLoop
  # rubocop:disable MethodLength
  def run
    i = 0
    loop do
      i += 1
      start = Time.now
      begin
        RubyCars::Base.all.each do |subclass|
          Runner.new(subclass.new).run
        end
      rescue => e
        RubyCarsLog.logger.warn "result=error error=#{e.class} message=\"#{e.message}\""
        next
      end
      finish = Time.now
      diff = finish - start
      puts "Run no.#{i} took #{diff} seconds"
      GC.start if i % 100 == 0
    end
  end
end
```

**Comment by kjoscha** [comment]
ich baue es einfach mal ein und deploye es... probieren geht über studieren ;)

**Comment by BenSto** [comment]
> ich baue es einfach mal ein und deploye es... probieren geht über studieren ;)

Brauchst Du nicht, ich habe es bereits probiert und der Garbage Collector scheint die Ruby Objekte nicht schnell genug wieder freizugeben. Inerhalb von 24h ist die Ram Auslastung von 0,5% trotzdem auf 1,0% gestiegen...

**Comment by BenSto** [comment]
closed, da wir nun erfolgreich cron jobs verwenden anstatt den infinite loop
